chore: switch to vercel and fix node 16 issues (#27)

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -61,34 +61,41 @@ jobs:
     runs-on: ubuntu-latest
     needs: [release]
 
+    env:
+      VERCEL_TOKEN: '${{ secrets.VERCEL_TOKEN }}'
+      VERCEL_ORG_ID: '${{ secrets.VERCEL_ORG_ID }}'
+      VERCEL_PROJECT_ID: '${{ secrets.VERCEL_PROJECT_ID }}'
+
     if: (github.event_name == 'workflow_dispatch' && contains(fromJson('["All", "Client"]'), github.event.inputs.app)) || (needs.release.outputs.releases_created && contains(fromJSON(needs.release.outputs.paths_released), 'client'))
 
     steps:
+      - name: Check Vercel Token
+        if: env.VERCEL_TOKEN == ''
+        run: |
+          echo 'You are missing the VERCEL_TOKEN secret!' \
+          exit 1
+
+      - name: Check Vercel Org ID
+        if: env.VERCEL_ORG_ID == ''
+        run: |
+          echo 'You are missing the VERCEL_ORG_ID secret!' \
+          exit 1
+
+      - name: Check Vercel Project ID
+        if: env.VERCEL_PROJECT_ID == ''
+        run: |
+          echo 'The VERCEL_PROJECT_ID secret is missing, this will deploy as a new site.' \
+          echo 'If you wanted to update a project instead, make sure to set the VERCEL_PROJECT_ID secret and run this deploy again!'
+
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0
 
-      - uses: actions/setup-node@v2
+      - name: Deploy to Vercel
+        uses: amondnet/vercel-action@v20
         with:
-          node-version: ${{env.NODE_VERSION}}
-
-      - name: Install
-        run: npm ci
-
-      - name: Build
-        run: npm run build --workspace client
-        env:
-          VITE_TITLE: 'Prod Title'
-          VITE_API_ADDR: '${{ secrets.API_URL }}'
-
-      - name: Deploy to Netlify
-        uses: nwtgck/actions-netlify@v1.2
-        with:
-          publish-dir: './client/dist'
-          production-branch: master
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          netlify-config-path: ./client/netlify.toml
-          github-deployment-environment: 'Production'
-        env:
-          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
-          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_API_ID }}
+          working-directory: './client'
+          vercel-token: '${{ secrets.VERCEL_TOKEN }}'
+          vercel-org-id: '${{ secrets.VERCEL_ORG_ID }}'
+          vercel-project-id: '${{ secrets.VERCEL_PROJECT_ID }}'
+          vercel-args: '--prod'
